name: aumigo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  dotenv: ^4.2.0
  build_runner: ^2.4.13
  flutter_dotenv: ^5.2.1
  bloc: ^9.0.0
  loading_animation_widget: ^1.3.0
  top_snackbar_flutter: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
    - .env

  
  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fontes/mplus/PlaywriteDKLoopet-ExtraLight.ttf
        - asset: assets/fontes/mplus/PlaywriteDKLoopet-Light.ttf
        - asset: assets/fontes/mplus/PlaywriteDKLoopet-Regular.ttf
        - asset: assets/fontes/mplus/PlaywriteDKLoopet-Thin.ttf

  
