name: ichat
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  build_runner: ^2.4.13
  provider: ^6.1.5+1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  bloc: ^9.0.0
  top_snackbar_flutter: ^3.3.0
  match: ^0.4.1
  validatorless: ^1.2.4
  flutter_bloc: ^9.1.1
  package_info_plus: ^9.0.0
  loading_animation_widget: ^1.3.0
  web_socket_channel: ^3.0.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  match_generator: ^0.4.2

flutter:

  uses-material-design: true

  assets:
    # - assets/images/
    # - assets/gif/
    - .env

    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
